version: "3"

services:
    flask_geo_dev:
        image: flask_geo_dev:1.00
        container_name: flask_geo_dev
        restart: unless-stopped
        command: manage.py runserver --host=0.0.0.0 --port=5001
        build:
            context: ../
            dockerfile: .dev-tools/Dockerfile
        ports:
            - "5001:5001"
        volumes:
            - ..:/usr/app